### PR TITLE
Interactive simulation

### PR DESCRIPTION
**Pull request by chrjo5**
@sjoelund This PR could need some assistance.

### CODE REVIEW

**Comment by sjoelund** [comment]
Yes, this won't merge because of conflcts... I could resolve them all except for SimulationDialog::simulationProcessFinished. Is the only change to the other code indentation? Then it could be written as the following and I could just copy-paste the function from the master branch:
```c++
if (simulationOptions.isInteractiveSimulation()) {
  getOpcUaClient(simulationOptions.getInteractiveSimulationPortNumber())->getSampleThread()->exit();
  getOpcUaClient(simulationOptions.getInteractiveSimulationPortNumber())->getOpcUaWorker()->pauseInteractiveSimulation();
  return;
}
```

**Comment by chrjo5** [comment]
Yes, the only change to the other code is just indentation and the code you wrote will work as intended.

**Comment by sjoelund** [comment]
I pushed the squashed merge. I didn't test it because I didn't have OMPlot or OMCompiler compiled. Look through it to see that it still works, and perhaps change the commit message to remove unnecessary parts.

**Comment by casella** [comment]
On the light side of it, if anybody out of this circle heard "I pushed the squashed merge" he/she would probably think of something very crude, or at least quite unpleaseant.

I had a flash with the feeling of squashed octopus in a food processor or something like that - probably some sub-conscious connection with the GIT cefalopods  :)

**Comment by chrjo5** [comment]
Just tested the squashed merge and it works mostly fine. However: 

`void SimulationDialog::simulationProcessRunning(SimulationOptions simulationOptions)`

Got an unintentional 'r': `VariablesWidget r*pVariablesWidget = MainWindow::instance()->getVariablesWidget();`

Is it easiest if you somehow push the change into your commit to keep them squashed or should I just commit it?

Also, got open62541.h include error despite using this commit: https://github.com/OpenModelica/OMCompiler/commit/1504ef744b3547f8fca2795f57dd1e4f1df0f1c6

I tested with the following include lines in OMEditGUI.pro:
`LIBS += -L$$PWD/../../open62541/build/ -lopen62541`
`INCLUDEPATH += $$PWD/../../open62541/build`
`DEPENDPATH += $$PWD/../../open62541/`

...which uses my locally open62541 build. Seems a bit strange since using the commit worked a few days ago. I've probably missed something.

Otherwise, it seems to work fine.

**Comment by adeas31** [comment]
The include path is wrong. It should be `$$OPENMODELICAHOME/include/omc/c` depending on my commit https://github.com/OpenModelica/OMCompiler/commit/1504ef744b3547f8fca2795f57dd1e4f1df0f1c6

Also I don't understand this `LIBS += -L$$PWD/../../open62541/build/ -lopen62541`. From where you get this library. I thought we are going to use `libomopcua.dll/so`.

**Comment by sjoelund** [comment]
If you used a local open62541 build, you might have gotten a different API version than the one we used, causing the conflicts.

**Comment by sjoelund** [comment]
I have a version that links now. I'll commit it when the baby falls asleep.

**Comment by chrjo5** [comment]
@sjoelund You are right. I can resolve the conflicts here or perhaps try to update the version you used? 

EDIT: Okay, awesome.

**Comment by sjoelund** [comment]
Oh, I fixed all those issues and I'll commit it soon. What I didn't fix was the win32 issues Adeel mentioned.

**Comment by adeas31** [comment]
I have fixed the windows linking and some other minor issues.
However, I can't test the code since every time I try to run the interactive simulation I get `Client unable to bind to the embedded simulation server over the port: 4841.` and after pressing the `cancel simulation` button OMEdit crashes in `SimulationDialog.cpp:1618` i.e., inside `SimulationDialog::simulationProcessFinished` method.

**Comment by chrjo5** [comment]
I'm building the code right now to test it but the signal comes from:
`void SimulationServerCheckThread::run()`

`if (!pTcpSocket->bind(mPort, QAbstractSocket::DontShareAddress)) {`
    `emit sendEmbeddedServerError();`
  `}`

Maybe it has to do with differences between port handling. I recognize the issue but thought I solved it. Building the code now to investigate the problem.

**Comment by adeas31** [comment]
It would be nice to see the actual socket error. So inside `embeddedServerError` method you could do
```
QTcpSocket *pTcpSocket= qobject_cast<QTcpSocket*>(const_cast<QObject*>(sender()));
pTcpSocket->errorString();
```

**Comment by chrjo5** [comment]
@adeas31 Yes, that's how it should be.

@sjoelund Is it something more I have to do to make the linking work? I get undefined references to UA_Types and the functions as well:
`OpenModelica/build/include/omc/c/open62541.h:2929: error: undefined reference to `UA_TYPES'`

**Comment by adeas31** [comment]
Perhaps you can directly typecast the sender,
`QTcpSocket *pTcpSocket= qobject_cast<QTcpSocket*>(sender());`

**Comment by adeas31** [comment]
Have you run the `configure` to get the new `OMEdit.config` file?

**Comment by chrjo5** [comment]
That was it, thank you very much.

I don't get the same error as you do regarding the socket. I'll se if there is another, better solution to it.

I also noticed that the variable names for writable variables look a bit strange. Seems like the value box somehow is melted into the name.

**Comment by chrjo5** [comment]
I think that the port handling should be better know (avoiding bind() and waiting for a connection instead). Test and see if it works. Also fixed the strange variables names mentioned above.

**Comment by adeas31** [comment]
Thanks. At least the connection error is gone now. But when I select and curve and click on play button then nothing is happening.

Also I think the QTcpSocket is unnecessary. Just start the simulation executable with the port 4841 if user don't specify any or use the user specified port and then connect `OpcUaClient` to it. I suggest to remove the `SimulationServerCheckThread` class.

If you have a strong case for keeping this class then speak now otherwise I am going to make a commit which will remove it.

**Comment by adeas31** [comment]
I have made a pull request that removes the `SimulationServerCheckThread` class https://github.com/chrjo5/OMEdit/pull/1

Test and merge it.

**Comment by chrjo5** [comment]
Yeah I guess it evolved into something unnecessary.

The play button issue is weird. It should just start calling `sample()` from the `OpcUaWorker`. I don't have this issue so I have to think about what it could be.

**Comment by adeas31** [comment]
OK. Then merge my pull request https://github.com/chrjo5/OMEdit/pull/1 since I don't have write access to your repository and I will investigate more about `OpcUaWorker`.

**Comment by adeas31** [comment]
`OpcUaWorker::sample()` is being called correctly so data is collected fine. It seems something is wrong with `QwtPlotDirectPainter` drawing.

**Comment by chrjo5** [comment]
I finally remember why `SimulationServerCheckThread` was there, while fixing the things related to OMPlot. For some reason, the embedded server takes some time before it is possible to connect to it, at least for me. Connecting to it directly can make the check `if (pOpcUaClient->connectToServer()) {` fail. The class was there to make sure that the signal was emitted when once the embedded server is ready.

I don't have a strong opinion about the best way to solve it (except making somehow make the server send the ready signal). Right now, I get "Could not connect to the embedded server." when I try to start a second interactive simulation of a different model.

I also have to look at why `QwtPlotDirectPainter` is not working for you. Right now, I have no idea.

**Comment by chrjo5** [comment]
I push the OMEdit changes to the new OMPlot control button 'API'.

**Comment by sjoelund** [comment]
For TCP/IP services, you need to have a loop with timeout, etc and retry if you fail to connect. It still fails to start on my Linux machine. (And when it fails to connect, the simulation dialog just sits there waiting)

**Comment by sjoelund** [comment]
If I recall correctly, the embedded server doesn't start until after initialization, which may take minutes (or hours). Perhaps this should be fixed in the interface, but it would probably mess up any assumptions (since you can't read or write variables until we have initialized them).

**Comment by adeas31** [comment]
I suggest we let the embedded server start and then send this information via the xmltcp output of simulation executable to OMEdit. OMEdit then try to connect to the embedded server.

I also think `embeddedServerPort` is not the best way. We should let server select the free port and then send this port number to OMEdit instead of asking OMEdit so tell which port to use.

**Comment by sjoelund** [comment]
@adeas31 I agree this sounds like a decent solution. I do like the embeddedServerPort as such since not everyone would want to use the xmltcp option, but for OMEdit we could have a way to use auto ports (either the default or setting the port to -1).

**Comment by adeas31** [comment]
https://github.com/OpenModelica/OMCompiler/pull/1724 outputs the information when opc-ua server is initialized. OMEdit reads that information and then create the opc-ua client and try to make a connection.

**Comment by sjoelund** [comment]
I still get in OMEdit:
```
[1] 07:56:48 Scripting Fel
Could not connect to the embedded server.
[2] 07:56:48 Scripting Notifiering
[07/12/2017 05:56:48.412] warning/network       Connection failed
```
The simulation output says:
```
stdout | info | <p>The embedded server is initialized.</p>
```
I am pretty sure I updated OMCompiler, OMPlot and OMEdit...

**Comment by sjoelund** [comment]
I no longer get a connection failure, but the interactive simulation doesn't start and there is no logging of the progress. It does start the simulation and it does initialize it; I can then connect via the opcua-client and run the simulation. But there is still nothing happening in OMEdit.

**Comment by adeas31** [comment]
@sjoelund this is exactly the same behavior I am experiencing on Windows.
@chrjo5 can you take a look at it now?

**Comment by chrjo5** [comment]
@adeas31 I'll be back home on Sunday and take a look on what's going on.

EDIT: Hmmm, I pulled the latest OMCompiler and ran the autoconf, make and everything compiles. However, I get a compilation error in OMEdit when I try to simulate the example models (same error on several models):

```
BouncingBall.c:327:4: error: initializer element is not a compile-time constant
   BouncingBall_functionRemovedInitialEquations,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23 warnings and 1 error generated.
<builtin>: recipe for target 'BouncingBall.o' failed
make: *** [BouncingBall.o] Error 1
make: *** Waiting for unfinished jobs....
Compilation process failed. Exited with code 2.
```

The warnings are about incompatible pointer types. Unfortunately, debugging the real issue is hard until I can compile the models. Good news is that I got plenty of time the next couple of weeks.

@adeas31 @sjoelund Any idea of what could be causing the compilation error?

**Comment by sjoelund** [comment]
Bah, no notification on comment edit. The error should be that the OMEdit and OMCompiler versions are out of sync (re-compile OMEdit after OMCompiler)

**Comment by sjoelund** [comment]
So it seems just adding a wait-loop makes the simulation start OK-ish. There are still problems with simulations that do not load properly (would now wait forever and you cannot close the simulation window to kill the process and OPC-UA thread). Real-time mode controlled by the simulation nodes i=10001 and i=10002, as well as unbounded simulations using node i=10003 do not work. There are also conflicts in the PR; we should fix those as soon as possible and at least have the step mode in the nightly.

**Comment by sjoelund** [comment]
@adeas31 - can you fix the conflicts? I added support for non-step mode as well. It seems to work as expected.

**Comment by sjoelund** [comment]
@adeas31 I rebased this PR and the OMPlot one; it now doesn't seem to work properly again. I'll see if I can figure out what's going wrong. Seems to be something with the start/pause buttons.

**Comment by sjoelund** [comment]
Never mind. `make clean` in OMPlot makes it work as expected again. @adeas31 you can now test this on Windows.

**Pull request merged**
