### PR TITLE
Link OMSimulator before OpenModelicaCompiler

### PR DESCRIPTION
**Pull request by adeas31**
Fixes the corrupt OMSimulator mat result file issue.

### CODE REVIEW

**Comment by adeas31** [comment]
@sjoelund can you test this on Linux and MAC. Linking the OMS after OM leads to a generation of corrupt mat file. I guess the mat writer of OM and OMS mess up. So I changed to link with OMS first.

**Comment by lochel** [comment]
@adeas31 @sjoelund This is crucial. Can we merge it?

**Comment by adeas31** [comment]
I talked with Martin about it yesterday and he thinks it is not a good idea. He suggests that we must prefix the function name of OMSimulator mat writer so that it doesn't mix up with OpenModelica. Also the preference level of binaries could vary on different versions of Linux.

**Comment by sjoelund** [comment]
I'm not sure it solves the underlying problem. Better would be to fix the linking by changing the name of the functions in OMSimulator. Even better would be a common library that both OMC and OMS used

⁣Sent from BlueMail ​

**Comment by lochel** [comment]
That's what I propose for quite some time now... Anyway, I have no time for such changes and will just move the Mat4 implementation to some namespace for now.

**Comment by sjoelund** [comment]
Oh yes. You can use namespaces since you use C++. That's a quite easy fix

**Comment by lochel** [comment]
Hopefully it will solve the problem: OpenModelica/OMSimulator#503

**Comment by lochel** [comment]
Result files are no longer corrupted in OMEdit 🎉

**Pull request closed without merging**
