### PR TITLE
Print a warning when no platforms are specified when generating an FMU (possibly related to ticket 4951)

### PR DESCRIPTION
**Pull request by atrosinenko**
I tried to reproduce an issue from the ticket 4951 by starting OMEdit without an `omedit.ini`, but instead of not generating an FMU, it generates an FMU with `sources`, `resources` and `modelDescription.xml` but without the `binary` subdirectory.

This PR introduces a warning about generating possibly incorrect FMU when None and no cross-targets is selected on the FMI tab of the Settings dialog (seems to be implicitly the case when no options were ever applied yet). If this is clearly defined behavior, then I should probably reword the message as referring to "source-only FMU" instead of "incorrect".

On the other hand, the warning is not fatal, since someone may wish to generate specifically a source-only FMU (not checked whether this compiles to the standard, though).

### CODE REVIEW

**Comment by atrosinenko** [comment]
I will try to substitute correct name for Options dialog slightly later, so it may be considered as WIP for now.

**Comment by atrosinenko** [comment]
Fixed hardcoded `Tools->Options`.

**Comment by adeas31** [comment]
I think we should improve this PR. First of all if there is no `omedit.ini` or the user doesn't have any platforms settings saved then we should use `static` as default for the platforms value. I suggest doing something like this in `MainWindow::exportModelFMU`,

```
if (!pSettings->contains("FMIExport/Platforms")) {
  platforms.append(OptionsDialog::instance()->getFMIPage()->getLinkingComboBox()->itemData(OptionsDialog::instance()->getFMIPage()->getLinkingComboBox()->currentIndex()).toString());
} else {
  platforms = pSettings->value("FMIExport/Platforms").toStringList();
}
```

Secondly, the message should say `source-only FMU` instead of `incorrect`.

**Comment by atrosinenko** [comment]
Thanks. Updated PR as suggested.

**Pull request merged**
