### PR TITLE
v1.11 updates

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by casella** [comment]
What about making this 1.11.0 Beta2, so it gets tested by other people?

**Comment by adrpo** [comment]
@casella, we need to port more commits from master to be able to build it on Windows. I'll try to do that tomorrow.

**Comment by adeas31** [comment]
I am working on WYSIWYG for documentation annotation. Hopefully I will be able to finish it tomorrow. So I suggest wait until Monday.

**Comment by hkiel** [comment]
I'm also working on OMNotebook to make it more usable.

**Comment by casella** [comment]
On Dec 8, the Board decided that that we release 1.11.0 before the Christmas break. There are only five days left next week to do so. Many important bugs have been fixed since the branch was made on Nov 29. 

Please do not delay 1.11.0 any further or possibly break it to add yet another feature to it in a hurry at the last minute. There is no reason to do so. The next 1.12.0 (or possibly 2.0.0) release is planned for March-April 2017, so it won't be long before new features are included in a stable release. We might actually do it earlier if there is enough new stuff to justify it.

My proposal is that @adrpo tags Beta2 as soon as he has pushed in all the necessary stuff to work on Windows (hopefully Monday), and that we release 1.11.0 on Thursday or Friday. That leaves a few days to double-check 1.11 Beta2 for any last-minute issue. If any other serious bug is found and fixed after the release, we should have a maintenance release 1.11.1 in January.

[Beta releases](https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta) by definition are meant to fix bugs discovered after feature freeze by beta testers, not to sneak in new features at the last minute, which might still be buggy. For this reason, IMHO any new feature such as WYSIWYG for documentation definitely belongs to 1.12.0.

Thanks!

**Pull request merged**
