### PR TITLE
ticket:5044 Allow setting the compiler

### PR DESCRIPTION
**Pull request by adeas31**
`--target=gcc` only set the makefile build system and not the compiler.
Use `setCompiler` and `setCXXCompiler` to set the compiler.

### CODE REVIEW

**Review by casella — APPROVED** [review]
Sounds good to me, as long as it works :)

**Comment by adeas31** [comment]
This how it looks on Windows now.

windows

**Comment by adeas31** [comment]
And this is how is looks in Linux,

linux

**Comment by adeas31** [comment]
@sjoelund can you test and check if it works according to what we discussed yesterday?

**Pull request merged**
