### PR TITLE
Added more viewing angles for 3D animation

### PR DESCRIPTION
**Pull request by robbr48**
Also some minor correction to colors of coordinate system axes.

### CODE REVIEW

**Comment by adeas31** [comment]
@robbr48  Can you fix the conflicts?

**Comment by vwaurich** [comment]
Your isometric perspective is nice but 17 perspectives in total is really a lot. I dont know any CAD-software or graphics editor that offers so many perspectives in that way. Basically 4 (iso, right, top, front) or 6 (iso, right, top, front, left bottom, back) would be sufficient . Providing rotated orthogonal views is atypical and this dropdown list is a bit overloaded. Maybe you can explain your intention?

**Comment by vwaurich** [comment]
I also would prefer the old default view since this suits all msl models (usually negative y points down). And I think the old icons are more intuitive and more familiar to CAD-users.

**Comment by robbr48** [comment]
The 17 viewing angles and their icons are taken directly from the BEAST multi-body tool by SKF.

The problem is that the vertical axis is not strictly defined. The animation mode is intended for two cases: Modelica 3D models and composite models for co-simulation. In Modelica, the axis of gravity can be changed to any axis in the World component. For co-simulation, each external model can use different vertical axes. Modelica use y as default, aircraft simulators typically use z, BEAST uses x and so on.

One option could be to add a "rotate camera by 90 degrees" button. In that case I believe 7 viewing angles would be sufficient, since the other ones can be accessed through rotation. Another idea could be to make it possible to choose vertical axis.

**Comment by vwaurich** [comment]
I think we should support the Modelica-use-cases first. Having -y pointing down is the same setting as in Dymola and it displays all models as one is used to. A button which rotates the view by 90 degrees is a really nice idea. Will you implement it?
I would also go for the old icon-stlye to code back/front/right/left/bottom/top with cube faces since this fits to the overall blueish-greyish-design of OMEdit, there is no color-coded coordinate system in Modelica and its more like you find it in other 3d-viewers. I can add some icons for left/back/bottom if you like.
Sorry for questioning your work. Just want to find the best solution. Next time we should discuss these things in advance.

BTW: How is this cosimulation feature meant to work? Is it result-file based visualization using mat or csv files?

**Comment by robbr48** [comment]
No problems. Right now we are focused on getting a working master simulation tool demonstrator for co-simulation ready before February. I guess we need to make sure the animation is harmonized to work well with both Modelica models and co-simulation models.

The co-simulations generate a CSV together with an XML file for animation. Adeel can probably explain the details better than me.

(actually the co-simulation framework does have color-coded coordinate systems, x=red, y=green, z=blue)

**Comment by vwaurich** [comment]
So you are using OMEdit to model cosimulations (using FMUs, I assume?). You need some kind of master algorithm to manage communication. Is omc going to be enhanced to do this or do you generate some kind of specification for a standalone tool that simulates? Is result-visualization going to be done with the current result-visualization?
I just want to understand your use-case and keep it in mind for further development of visualization.

**Comment by casella** [comment]
For the record,  having -y pointing down is not Dymola-specific but rather comes from the Modelica Standard Library, where the definition of the default direction of the gravity vector in `Modelica.Mechanics.MultiBody.World` reads

`parameter Types.Axis n={0,-1,0};`

**Comment by casella** [comment]
@robbr48: we could have some pre-defined MSL-compliant views in the tool

**Comment by adeas31** [comment]
@casella We can make the tool show views which are suitable for both Modelica & co-simulation. I just updated the code to handle it.
@vwaurich FMUs are one part of co-simulation. OMC is not going to be enhanced. SKF has done TLM based co-simulation. OMEdit will only be used for modeling and calling the co-simulation framework which will generate a csv result file then OMEdit use that result file for post processing i.e, plotting and animation.

**Comment by vwaurich** [comment]
I see. Thanks for information and for the code update.

**Pull request closed without merging**
