### PR TITLE
propagate threadData from main.cpp

### PR DESCRIPTION
**Pull request by adrpo**
this approach to propagate threadData from main.cpp seems to work
@adeas31 , can you check if this also fixes the FMU generation crash?

### CODE REVIEW

**Comment by adeas31** [comment]
Should I test it with local or global symboltable?

**Comment by sjoelund** [comment]
Try with local

**Review by adeas31 — APPROVED** [review]
I modified the code a bit. Just move the threadData pointer to OMCInterface. Everything seems to work even the FMU export.

**Comment by adeas31** [comment]
@sjoelund did you test this on Linux?

**Comment by sjoelund** [comment]
@adeas31 No. I just assume Linux works. It almost always does :)

**Pull request merged**
