### PR TITLE
Do not pass platform triplets with '&' when compiling FMUs (ticket #4139)

### PR DESCRIPTION
**Pull request by atrosinenko**
This fixes the issue when built on my Ubuntu 18.04 (though, not tested with the Docker image for build server).

Technically, this will reset previous FMU platform settings, but these are most probably were not working anyway.

### CODE REVIEW

**Comment by adeas31** [comment]
@sjoelund Can you please test this?

**Comment by sjoelund** [comment]
Is this another problem with the accelerator being added to the text? If so you should rather set a data section for the checkbox and get the data instead of the text (which Qt does weird things to).

**Comment by atrosinenko** [comment]
I have rewritten it using a property. It has a "magic string" id, but this seems to be quite common in that file. I can rewrite it using named constant if you wish (but what is the preferred way: `static const QString` in the class / member of an anonymous namespace / `#define`?).

**Comment by adeas31** [comment]
I think `static const QString` in the class is fine.

**Comment by atrosinenko** [comment]
Thanks. Fixed.

**Comment by adeas31** [comment]
Sorry, my bad. I misunderstood your question. I guess in that case we should use the `Helper` class.

I agree there are several string ids used in that file. I think we should have a separate namespace for them.

**Comment by adeas31** [comment]
@sjoelund can you test this now?

**Comment by atrosinenko** [comment]
Ping. (Or is this postponed to the next release cycle too? Meanwhile, is there some expected date of 1.13 release?)

**Comment by adeas31** [comment]
This can go in 1.13 but @sjoelund doesn't have time to test it. I will test it myself on my ubuntu VM.
1.13 is expected soon but there is no final date. We have planned to release a beta first. @adrpo when will be 1.13 beta available?

**Comment by atrosinenko** [comment]
I'm not insisting on this being in 1.13, I'm just asking. :) This is just some not essential option in UI that does not work presently, though. After all, this functionality is more required on build server that anyway would use `.mos`-scripts and for local system type builds it is already working. The release date interests me more because it blocks possibility of merging code completion feature.

**Comment by atrosinenko** [comment]
So **for me** it is fine to postpone this PR until the next release.

**Review by adeas31 — APPROVED** [review]

**Pull request merged**
