### PR TITLE
Fmu settings

### PR DESCRIPTION
**Pull request by vwaurich**
Before simulation of FMUs in the visualization window, a dialog to set solver, stepsize, and eventiteration pops up.

### CODE REVIEW

**Comment by adeas31** [comment]
Why have you used `QMainWindow` for fmu settings dialog? Update it to `QDialog`.

At some places you call it `FMUSettingsWindow` and at some places you call it `FMUSettingsDialog`. Would be nice to use one naming convention otherwise its confusing. I recommend `FMUSettingsDialog`.

Open the dialog with `exec` function to make it modal.

You don't need this many layout objects,
```
QVBoxLayout *mainLayout = new QVBoxLayout;
  QHBoxLayout *buttonLayout = new QHBoxLayout;
  QHBoxLayout *visualizationLayout = new QHBoxLayout;
  QVBoxLayout *visLeftLayout = new QVBoxLayout;
  QVBoxLayout *visRightLayout = new QVBoxLayout;
  QHBoxLayout *simulationLayout = new QHBoxLayout;
  QVBoxLayout *simLeftLayout = new QVBoxLayout;
  QVBoxLayout *simRightLayout = new QVBoxLayout;
```
You have a pretty simple dialog which can be done via one `QGridLayout`.

**Comment by vwaurich** [comment]
Thanks for the review. I integrated your remarks.

**Comment by adeas31** [comment]
Thanks for fixing this but there are still some issues,

I don't understand why you need another QDialog inside `FMUSettingsDialog`?
Remove the `mpSettingsDialog` and the extra layout object `mainLayout`. Use the `setLayout` to set the layout of `FMUSettingsDialog` (See as example `ModelicaClassDialog`, `DuplicateClassDialog` or `ImportFMUDialog`).

Call `FMUSettingsDialog` with exec,
```
mpFMUSettingsDialog = new FMUSettingsDialog(this, fmuVisualizer);
mpFMUSettingsDialog->exec();
```
Note that you need to `accept` and `reject` the dialog so that exec can get a proper value. `close` is not the proper way.

You also don't need to delete `QLineEdit`, `QCheckBox` etc. since Qt automatically takes cares of the classes inherited from QObject. So we can get rid of the destructor.

**Comment by adeas31** [comment]
Also its good idea to set a parent for the base class so update from,
`: QDialog()`
to
`: QDialog(pParent)`

**Comment by vwaurich** [comment]
If I do this, OMEdit crashes when closing the animation widget Although the dialog should be closed.

**Comment by adeas31** [comment]
It should not. Have you tried debugging it why its happening?
Well update and push your changes and we will see if it still happens.

**Comment by adeas31** [comment]
It is crashing when you trying to delete QLineEdit,
`delete mpStepsizeLineEdit;`
As I said earlier you don't need to delete Qt objects. Qt garbage collector will take care of it.

I also suggest to use `setAttribute(Qt::WA_DeleteOnClose);` so the dialog is destroyed right after it is closed and you can get rid of `FMUSettingsDialog *mpFMUSettingsDialog;` from `AbstractAnimationWindow.h` and update the code of `openFMUSettingsDialog` as,

```
FMUSettingsDialog *pFMUSettingsDialog = new FMUSettingsDialog(this, fmuVisualizer);
pFMUSettingsDialog->exec();
```

**Comment by vwaurich** [comment]
I havent adapted anything except changing the type of FMUSettingsDialog to QDialog. Thats why there was a double dialog and the messy rest. Its working now.

**Pull request merged**
