### PR TITLE
update translation files

### PR DESCRIPTION
**Pull request by hkiel**
translate some german strings

### CODE REVIEW

**Comment by adeas31** [comment]
Why they need to be in English?

**Comment by hkiel** [comment]
In DocumentationWidget.cpp:825 there is code searching for values in the drop down box:
```
QString format = queryCommandValue("formatBlock");
int currentIndex = mpStyleComboBox->findData(format);
```
so, my guess was that these are distinct (untranslatable) keywords for `Normal` or `Heading 1`.

**Comment by adeas31** [comment]
The search is on data not on the display string.
The data is second argument i.e., p, h1, h2....

**Comment by hkiel** [comment]
@adeas31 Okay, understood. I removed that part of the patch. Now only the translation files are updated (including some german translations)

**Review by adeas31 — APPROVED** [review]

**Pull request merged**
