### PR TITLE
option to animate FMUs

### PR DESCRIPTION
**Pull request by vwaurich**
OMEdit can animate FMUs (me 1.0) with realtime synchronization and forward euler as solver
FMIlib headers are included which cause a lot of annoying warnings.
Should be doing it on linux as well.

### CODE REVIEW

**Comment by rfranke** [comment]
It's a pity you don't support FMI 2 that significantly cleaned up and improved the interface. Shouldn't FMI 1 be considered obsolete?

**Comment by vwaurich** [comment]
We should support both versions anyway, should'nt we? If I get this commit into master and everything is fine with the build, I can continue further development and add 2.0 support.

**Comment by sjoelund** [comment]
No, we should not spend any effort on support for FMI 1.0. 2.0 is much more important.

**Comment by vwaurich** [comment]
I will add FMI 2.0 support. Should I keep support for FMI 1.0 at all?

**Comment by casella** [comment]
If it's already there, why not. One might have some legacy application which needs it. FMI 1.0 hasn't been declared obsolete. But if doing that hampers a full 2.0 implementation, I would happily sacrifice it

**Comment by vwaurich** [comment]
I have added some basic FMU 2.0 support https://github.com/OpenModelica/OMEdit/pull/53
next to FMU 1.0

**Pull request closed without merging**
